# Generated by Django 3.2.19 on 2023-07-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
